import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { TasksProvider } from "@/contextStore/task";
import { TimerProvider } from "@/contextStore/timer";
import { ThemeProvider } from "@/contextStore/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar.";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TimerProvider>
            <TasksProvider>
              <Navbar />
              {children}
              <Toaster />
            </TasksProvider>
          </TimerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
